#server:
#  port: 8585

#spring:
#  application:
#    name: API-GATEWAY

 # cloud:
#    gateway:
 #     routes:
 #     - id: CUSTOMERS-MS
 #       uri: http://localhost:8181/
 #       predicates:
 #       - path = /customers/** 
           
 #     - id: CUSTOMERS-MS
 #       uri: http://localhost:8181/
  #      predicates:
  #      - path = /customers/** 
