#server:
# port: 9876
 

server:
  port: 9999 
  
spring:
  application:
    name: CUSTOMER-MS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_db
    username: root
    password: Yashaswini@23
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
